name: Docker Image Build

on:
    workflow_dispatch: {}
    push:
        paths-ignore:
            - '.infra/**'
            - '.github/**'
        branches-ignore:
          - main

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v2.6.0
    secrets: inherit
    with:
      env: rdev
      images: |
        [
          {
            "name": "backend",
            "context": ".",
            "dockerfile": "Dockerfile",
            "platform": "linux/arm64"
          },
          {
            "name": "frontend",
            "context": "./hello/frontend",
            "dockerfile": "Dockerfile",
            "platform": "linux/arm64"
          }
        ]
